import NavBar from "./(components)/NavBar/NavBar";
import Footer from "./(components)/Footer/Footer";
import "./(styles)/globals.scss";
import localFont from "next/font/local";

const myFont = localFont({
  src: [
    {
      path: "../../fonts/Lato/latolight.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../fonts/Lato/latoregular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../fonts/Lato/latomedium.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-lato",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ua">
      <body className={myFont.variable}>
        <NavBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
